### ISSUE TITLE
When I run command I get many errors and no iptables are edited

### ISSUE THREAD

**Issue by mladja04** [Reiser89/plesk-centos-firewall-opener#1]
My server is 
centos-release-6-7.el6.centos.12.3.x86_64

[root@ ~]# ./fwplesk.sh
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 13: firewall-cmd: command not found
./fwplesk.sh: line 18: firewall-cmd: command not found
./fwplesk.sh: line 21: firewall-cmd: command not found
Following ports are open on your firewall:
./fwplesk.sh: line 24: firewall-cmd: command not found
Done!

What can be problem?

Thank you.

**Comment by Reiser89** [comment]
Hi,

this only works on **Centos 7+**, sorry.
Centos 6 does not come with firewalld.

I would recommend you to upgrade to Centos 7 if you can.


best regards
